version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 20s
      timeout: 5s
      retries: 5
    container_name: postgres
  

  api:
    build:
      context: .
    ports:
      - ${API_PORT}:${API_CONTAINER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend


volumes:
  pgdata: